name: deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.2.3'

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and Check Package
        uses: hynek/build-and-inspect-python-package@v2.6.0
        with:
          attest-build-provenance-github: true
